# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('property_size', models.IntegerField()),
                ('year_built', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
            ],
        ),
    ]
