# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20170512_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='age_of_construction',
            field=models.CharField(choices=[('LESS THAN A YEAR OLD', 'Less than a year old'), ('1 TO 3 YEARS OLD', '1 to 3 years old'), ('3 TO 5 YEARS OLD', '3 to 5 years old'), ('5 TO 10 YEARS OLD', '5 to 10 years old'), ('GREATER THAN 10 YEARS OLD', 'Greater than 10 years old')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='attached_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='attached_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='club_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='corner_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='day_care_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='expected_monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='food_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='garden_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='garden_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='main_road_facing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='maintenance_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_floors',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_parking_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='other_charges',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pg_availability',
            field=models.CharField(blank=True, choices=[('MALE_ONLY', 'Male Only'), ('FEMALE_ONLY', 'Female Only'), ('CO-ED', 'Co-ed')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='pg_occupancy_availability',
            field=models.CharField(blank=True, choices=[('SINGLE_ONLY', 'Single Only'), ('SHARING_ONLY', 'Sharing Only'), ('BOTH', 'Both')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='play_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='play_area_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_backup_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_hours',
            field=models.CharField(blank=True, choices=[('8 HOURS', '8 hours'), ('16 HOURS', '16 hours'), ('24 HOURS', '24 hours')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='water_source',
            field=models.CharField(blank=True, choices=[('CORPORATION', 'Corporation'), ('BOREWELL', 'Borewell'), ('TANKERS', 'Tankers')], default='', max_length=30),
        ),
    ]
